<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>9795ebcf-544d-4aeb-bef3-a60bfc7d8999</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='phoneloginModal']/div[3]/div/div/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.style-prefix-c2uxn6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5243ef30-7666-4676-a46a-b795bf58c28a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>162c3d58-b140-4ee2-acb2-c9e558df7fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-prefix-c2uxn6</value>
      <webElementGuid>12cd3bc8-1e49-405e-8f80-473e22597691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>f36e6078-405f-438e-8c88-6d1599ec35d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phoneloginModal&quot;)/div[@class=&quot;style-prefix-pbmsma&quot;]/div[@class=&quot;style-prefix-17k3sa9&quot;]/div[@class=&quot;style-prefix-lv607q&quot;]/div[@class=&quot;style-prefix-13owxp7&quot;]/button[@class=&quot;style-prefix-1xr80lg&quot;]/span[@class=&quot;style-prefix-c2uxn6&quot;]</value>
      <webElementGuid>41361d6f-dcec-4807-8fad-4217e7997937</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='phoneloginModal']/div[3]/div/div/div/button/span</value>
      <webElementGuid>9f806fa5-ed86-4de2-a8b3-17479607684b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Mode'])[1]/following::span[1]</value>
      <webElementGuid>250f3c63-afd9-4e22-ba69-ae5b3116bc96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='download android app'])[1]/following::span[2]</value>
      <webElementGuid>65b335b0-81d3-4406-b837-b682776c8cf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::span[1]</value>
      <webElementGuid>2bfe451f-5b37-46bf-82db-5b90bac07386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTINUE'])[1]/preceding::span[2]</value>
      <webElementGuid>91eae8f4-73ac-432c-b16b-aeb44a10b673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='×']/parent::*</value>
      <webElementGuid>29ea9427-9888-4d81-ae37-080d76d7eea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>bdbc4e04-00f8-4919-97b3-73cf50b35da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '×' or . = '×')]</value>
      <webElementGuid>38f27d1b-895d-4786-bc72-f9c59afa121b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
