<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Spin Bike_style-prefix-1iji7yj</name>
   <tag></tag>
   <elementGuidId>e9199a82-3871-444e-b898-7b75974ce636</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='plp-container']/div[2]/div/div/a/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8842e853-8c05-4c7b-b0da-3d3573c210ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn-images.cure.fit/www-curefit-com/image/upload/fl_progressive,f_auto,q_auto:eco,w_300,h_400,ar_0.75,c_fill/dpr_2/cultgear-content/SH2C5YdLTPJuRNN3gPiQpgrX</value>
      <webElementGuid>084c94b5-1799-4208-bbbc-2bbb42f42089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>OFP-1001 Static Handle with Backrest Upright Stationary Exercise Bike</value>
      <webElementGuid>8f0a07e6-dd08-45fc-99ce-dfed8dddf485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> style-prefix-1iji7yj</value>
      <webElementGuid>9c0e68d9-ef8f-4e81-9815-d2c33c5e2fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>326b358a-6e5b-4860-b533-890dcce575d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>3ff1fa66-4c7d-4721-a318-0b9cbf6208a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>1139a932-c11b-4eac-a756-035f533aa105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;plp-container&quot;)/div[@class=&quot;animate-tb&quot;]/div[@class=&quot;style-prefix-ikbfam&quot;]/div[@class=&quot;col-xs-6 col-lg-3 col-md-3 col-sm-6 animate-tb noPadding style-prefix-prstg&quot;]/a[@class=&quot;style-prefix-0&quot;]/div[@class=&quot;style-prefix-12pfcno&quot;]/div[@class=&quot;style-prefix-xcvqlr&quot;]/img[@class=&quot;style-prefix-1iji7yj&quot;]</value>
      <webElementGuid>36afecdb-4f8f-4ad0-b3a0-e41a7b51634d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='plp-container']/div[2]/div/div/a/div/div/img</value>
      <webElementGuid>15299b2b-dbf4-48e5-af3f-46f05f5a1d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='OFP-1001 Static Handle with Backrest Upright Stationary Exercise Bike']</value>
      <webElementGuid>f5eaa387-f677-4a58-93da-0ed99da342b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div/img</value>
      <webElementGuid>146635ed-30f3-4362-bdec-afc5ae05deac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn-images.cure.fit/www-curefit-com/image/upload/fl_progressive,f_auto,q_auto:eco,w_300,h_400,ar_0.75,c_fill/dpr_2/cultgear-content/SH2C5YdLTPJuRNN3gPiQpgrX' and @alt = 'OFP-1001 Static Handle with Backrest Upright Stationary Exercise Bike']</value>
      <webElementGuid>d60713d7-8118-4457-abfb-f52726716afa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
