<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_974_plus-sign</name>
   <tag></tag>
   <elementGuidId>8c2b3713-47b1-47cd-bdbf-2e1393649c81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gear-cart']/div/div/div/div[2]/div[2]/div/img[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.plus-sign</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e9eb4030-e1b8-4a55-a48b-ed1a90ff6f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>plus-sign</value>
      <webElementGuid>c66c8cc7-eaea-4143-88d5-79898243be1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static.cure.fit/assets/images/plus.svg</value>
      <webElementGuid>8a8e5fcb-dc3d-4603-a471-8881e5a6c9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gear-cart&quot;)/div[@class=&quot;gear-cart-item&quot;]/div[@class=&quot;style-prefix-tr0r3x&quot;]/div[@class=&quot;style-prefix-171qv4g&quot;]/div[@class=&quot;style-prefix-190oc8g&quot;]/div[2]/div[@class=&quot;style-prefix-cv2pe&quot;]/img[@class=&quot;plus-sign&quot;]</value>
      <webElementGuid>6f2f341c-404a-4c16-97b2-a80fba835b2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gear-cart']/div/div/div/div[2]/div[2]/div/img[2]</value>
      <webElementGuid>1ca893f6-cf0b-400a-b4b2-52003cc882bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://static.cure.fit/assets/images/plus.svg')]</value>
      <webElementGuid>7151e8fa-2331-4c5f-a955-37703e01d7e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>4b2a4fd0-6b40-4977-942c-eac38a2c7947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://static.cure.fit/assets/images/plus.svg']</value>
      <webElementGuid>5fc0f735-92f5-4024-a5b7-49eee31a6a54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
