<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sign in with Google</name>
   <tag></tag>
   <elementGuidId>5f5316c7-7fea-450f-a10d-f5272fd89470</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='loginModal']/div[3]/div/div/div/div/div/div[2]/div/span/div/button/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.style-prefix-lqps2a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d3f08408-26c1-4bb5-bea0-254408fab9f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-prefix-lqps2a</value>
      <webElementGuid>189806f9-8b40-4f7c-ad34-919eee7e9e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in with Google</value>
      <webElementGuid>ad1b7650-b4f9-4e11-a193-d69ff5613906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginModal&quot;)/div[@class=&quot;style-prefix-pbmsma&quot;]/div[@class=&quot;style-prefix-1lr2hzl&quot;]/div[@class=&quot;style-prefix-lv607q&quot;]/div[@class=&quot;style-prefix-mfhl81&quot;]/div[@class=&quot;style-prefix-19ffg0l&quot;]/div[@class=&quot;style-prefix-16sdzfa&quot;]/div[@class=&quot;style-prefix-46b038&quot;]/div[@class=&quot;style-prefix-eroe8x&quot;]/span[@class=&quot;style-prefix-70qvj9&quot;]/div[@class=&quot;style-prefix-ly73ju&quot;]/button[@class=&quot;style-prefix-aavrz2&quot;]/div[@class=&quot;button_text style-prefix-zmnbeb&quot;]/div[@class=&quot;style-prefix-lqps2a&quot;]</value>
      <webElementGuid>b4c76c5f-1d6d-4fbd-aa1e-099e1d05aec7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loginModal']/div[3]/div/div/div/div/div/div[2]/div/span/div/button/div/div[2]</value>
      <webElementGuid>a7b13615-9bfc-40ce-b3c3-53e401cf4fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::div[7]</value>
      <webElementGuid>c33152b9-1869-4c31-a1a4-fe1266fa5cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Mode'])[1]/following::div[21]</value>
      <webElementGuid>22e12759-e72f-41d8-9c55-83861b4c774a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in with email'])[1]/preceding::div[3]</value>
      <webElementGuid>e4586e69-4c14-42a0-abbc-901d95c92027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign in with Google']/parent::*</value>
      <webElementGuid>f47992d5-52dc-42cb-95f8-ddc7e9c32460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div[2]</value>
      <webElementGuid>6d2a8a93-3cee-4b6b-84c0-57bef0c8a00f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sign in with Google' or . = 'Sign in with Google')]</value>
      <webElementGuid>370ff762-c191-459d-8181-c1cbd04b6f53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
