<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_5359_plus-sign</name>
   <tag></tag>
   <elementGuidId>521ff9a9-faa1-4e19-b443-5a3e09aee7e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gear-cart']/div/div/div/div[2]/div[2]/div/img[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.plus-sign</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e8b4b417-d28d-45a8-9892-fcec17b03d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>plus-sign</value>
      <webElementGuid>731daf4f-436d-4a86-8361-5a3031d29536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static.cure.fit/assets/images/plus.svg</value>
      <webElementGuid>ab6b8418-cec5-4d9e-8d0c-d310871165bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gear-cart&quot;)/div[@class=&quot;gear-cart-item&quot;]/div[@class=&quot;style-prefix-tr0r3x&quot;]/div[@class=&quot;style-prefix-171qv4g&quot;]/div[@class=&quot;style-prefix-190oc8g&quot;]/div[2]/div[@class=&quot;style-prefix-cv2pe&quot;]/img[@class=&quot;plus-sign&quot;]</value>
      <webElementGuid>14a39e75-4096-469c-b170-9ecfb516365d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gear-cart']/div/div/div/div[2]/div[2]/div/img[2]</value>
      <webElementGuid>3239c142-e8d4-4e99-90fa-9e232e22938d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://static.cure.fit/assets/images/plus.svg')]</value>
      <webElementGuid>141c5503-d920-4e25-ba6f-afedb14c9793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>fd64af63-ca20-4b9f-95c4-1ef49bc930bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://static.cure.fit/assets/images/plus.svg']</value>
      <webElementGuid>db840745-e25a-4697-a329-1e9883957c4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
