<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_OR_style-prefix-ue3i0g</name>
   <tag></tag>
   <elementGuidId>3d05dd34-1ab7-41a0-8c95-2f402139ccab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='phoneloginModal']/div[3]/div/div/div[2]/div/div[2]/div[3]/button/div/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.style-prefix-ue3i0g</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d1d3a6d0-2c90-43c9-bac1-06cb19750e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn-images.cure.fit/www-curefit-com/image/upload/c_fill,w_24,ar_1,q_auto:eco,dpr_2,f_auto,fl_progressive//image/cultsport/assets/google-logo.png</value>
      <webElementGuid>b4c27371-b142-4b1e-87bf-f0cdf22d9cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-prefix-ue3i0g</value>
      <webElementGuid>a6acac65-89d2-4d6d-8140-a5ac22ce5d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phoneloginModal&quot;)/div[@class=&quot;style-prefix-pbmsma&quot;]/div[@class=&quot;style-prefix-17k3sa9&quot;]/div[@class=&quot;style-prefix-lv607q&quot;]/div[@class=&quot;style-prefix-mfhl81&quot;]/div[@class=&quot;style-prefix-1j61q1z&quot;]/div[@class=&quot;style-prefix-1nr9jr0&quot;]/div[@class=&quot;style-prefix-qtcbab&quot;]/button[@class=&quot;style-prefix-ozt8il&quot;]/div[@class=&quot;button_text style-prefix-zmnbeb&quot;]/div[@class=&quot;style-prefix-x4dmss&quot;]/div[@class=&quot;style-prefix-7kp13n&quot;]/img[@class=&quot;style-prefix-ue3i0g&quot;]</value>
      <webElementGuid>b4e31777-a8d5-44b0-99a4-4a6ab5ef030e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='phoneloginModal']/div[3]/div/div/div[2]/div/div[2]/div[3]/button/div/div/div[2]/img</value>
      <webElementGuid>33cdebeb-7be1-4d56-b901-fa1cdf32666f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://cdn-images.cure.fit/www-curefit-com/image/upload/c_fill,w_24,ar_1,q_auto:eco,dpr_2,f_auto,fl_progressive//image/cultsport/assets/google-logo.png')]</value>
      <webElementGuid>d1f04b90-50c9-4dc4-b20e-8cfa61cbf954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div/div[2]/img</value>
      <webElementGuid>52fff8d8-58e9-4935-8943-1ba9e152f795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn-images.cure.fit/www-curefit-com/image/upload/c_fill,w_24,ar_1,q_auto:eco,dpr_2,f_auto,fl_progressive//image/cultsport/assets/google-logo.png']</value>
      <webElementGuid>c3ff2905-c139-467b-aa2e-fb9792534982</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
