<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_LAYR Solid Sweatshirt_style-prefix-1iji7yj</name>
   <tag></tag>
   <elementGuidId>8812e5d6-0cf8-4f7a-a928-e02bbcddc759</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='679de0d1-5c3c-4412-be1d-730c4458148d1399flydry_cotton2.20WEformfitfab-CS-tenant']/div/div[2]/div/div/div[2]/div[6]/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>af84d6fc-9e6c-482f-902e-f427995a81a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn-images.cure.fit/www-curefit-com/image/upload/fl_progressive,f_auto,q_auto:eco,w_300,h_400,ar_0.75,c_fill/dpr_2/cultgear-content/Wv3uA2uG94vW1Ai7QzKp5sDp</value>
      <webElementGuid>275e13f6-f783-48fe-b851-71b6dd5b47bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Solid Workout Shorts</value>
      <webElementGuid>8a88b3c2-acc2-49a6-bc8e-739e760ca950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> style-prefix-1iji7yj</value>
      <webElementGuid>02c680b2-2e20-471b-b0c4-e190f6400da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>27964232-1fc1-44c0-9f15-a78eb3bdcf15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>e677661b-83cf-4ce5-b74d-c8548b19f059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>b5ba1018-c10f-470c-93d2-930fddcd0174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;679de0d1-5c3c-4412-be1d-730c4458148d1399flydry_cotton2.20WEformfitfab-CS-tenant&quot;)/div[@class=&quot;clearfix&quot;]/div[@class=&quot;container content style-prefix-1v6lej7&quot;]/div[1]/div[@class=&quot;style-prefix-1ylf8ir&quot;]/div[@class=&quot;style-prefix-1wccbw5&quot;]/div[@class=&quot;style-prefix-dfiblk&quot;]/div[@class=&quot;style-prefix-bq7m8f&quot;]/div[@class=&quot;style-prefix-12pfcno&quot;]/div[@class=&quot;style-prefix-xcvqlr&quot;]/img[@class=&quot;style-prefix-1iji7yj&quot;]</value>
      <webElementGuid>91371064-898f-48e7-af71-da5734386da4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='679de0d1-5c3c-4412-be1d-730c4458148d1399flydry_cotton2.20WEformfitfab-CS-tenant']/div/div[2]/div/div/div[2]/div[6]/div/div/div/img</value>
      <webElementGuid>6261bf85-e7b2-4010-b60c-5e065845b7f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Solid Workout Shorts']</value>
      <webElementGuid>7ab97a03-7729-4934-910a-d3d74a23511c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/img</value>
      <webElementGuid>e1bddad2-8d45-4908-8814-28501947de2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn-images.cure.fit/www-curefit-com/image/upload/fl_progressive,f_auto,q_auto:eco,w_300,h_400,ar_0.75,c_fill/dpr_2/cultgear-content/Wv3uA2uG94vW1Ai7QzKp5sDp' and @alt = 'Solid Workout Shorts']</value>
      <webElementGuid>279f7ba4-88f3-474b-af90-24535f6a8a87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
