<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_FormFit High Impact Ivy Sports Bra_styl_4ce653</name>
   <tag></tag>
   <elementGuidId>7613024d-7e6d-447f-a744-3f26386fc01e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='plp-container']/div[2]/div/div[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0a2f4df7-812d-4c12-97d2-695fb346968f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn-images.cure.fit/www-curefit-com/image/upload/fl_progressive,f_auto,q_auto:eco,w_300,h_400,ar_0.75,c_fill/dpr_2/cultgear-content/8vVR6uLBQSmX2vMsh6hfkXT2</value>
      <webElementGuid>8a3f0045-773b-4af0-b61a-4483fb72b7cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Vitals Running T-Shirt</value>
      <webElementGuid>2a7c771d-7801-447a-b2b4-3d83f8a76cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> style-prefix-1iji7yj</value>
      <webElementGuid>99cca105-caa5-4f22-abb1-6080f514e5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>9794eb6f-944e-423f-a5ac-71edceddc4d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>fa7b9bd5-c993-4f59-a92f-4aabfbe745ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>02e80e6e-1e32-43ca-a465-2e7096a8ccf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;plp-container&quot;)/div[@class=&quot;animate-tb&quot;]/div[@class=&quot;style-prefix-ikbfam&quot;]/div[@class=&quot;col-xs-6 col-lg-3 col-md-3 col-sm-6 animate-tb noPadding style-prefix-prstg&quot;]/div[@class=&quot;style-prefix-12pfcno&quot;]/div[@class=&quot;style-prefix-xcvqlr&quot;]/img[@class=&quot;style-prefix-1iji7yj&quot;]</value>
      <webElementGuid>03c78e0f-740a-4739-9852-0e2f9ab992ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='plp-container']/div[2]/div/div[2]/div/div/img</value>
      <webElementGuid>d1546743-3821-4f4a-877c-9dbeb0e90bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Vitals Running T-Shirt']</value>
      <webElementGuid>f3562d6d-d259-46bd-b16c-98bc88a111db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/img</value>
      <webElementGuid>408c3a30-78f9-45a3-b53d-b58395887865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn-images.cure.fit/www-curefit-com/image/upload/fl_progressive,f_auto,q_auto:eco,w_300,h_400,ar_0.75,c_fill/dpr_2/cultgear-content/8vVR6uLBQSmX2vMsh6hfkXT2' and @alt = 'Vitals Running T-Shirt']</value>
      <webElementGuid>b9d95978-c4c4-4f23-b6a4-682dc5f024f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
