<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sign in with Google</name>
   <tag></tag>
   <elementGuidId>311eac91-4dcb-4d01-9ca9-6132f7c20510</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='loginModal']/div[3]/div/div/div/div/div/div[2]/div/span/div/button/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.style-prefix-lqps2a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>552a8953-658e-4d2c-b5c6-011fc4b6077c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-prefix-lqps2a</value>
      <webElementGuid>a2197824-09ad-4662-b4a9-1ffd72b92d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in with Google</value>
      <webElementGuid>041d9955-a8b0-49a2-ba2d-00c87abf048f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginModal&quot;)/div[@class=&quot;style-prefix-pbmsma&quot;]/div[@class=&quot;style-prefix-1lr2hzl&quot;]/div[@class=&quot;style-prefix-lv607q&quot;]/div[@class=&quot;style-prefix-mfhl81&quot;]/div[@class=&quot;style-prefix-19ffg0l&quot;]/div[@class=&quot;style-prefix-16sdzfa&quot;]/div[@class=&quot;style-prefix-46b038&quot;]/div[@class=&quot;style-prefix-eroe8x&quot;]/span[@class=&quot;style-prefix-70qvj9&quot;]/div[@class=&quot;style-prefix-ly73ju&quot;]/button[@class=&quot;style-prefix-aavrz2&quot;]/div[@class=&quot;button_text style-prefix-zmnbeb&quot;]/div[@class=&quot;style-prefix-lqps2a&quot;]</value>
      <webElementGuid>4bc10537-b9fb-4fa8-ae33-94a712cdde26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loginModal']/div[3]/div/div/div/div/div/div[2]/div/span/div/button/div/div[2]</value>
      <webElementGuid>9ae09346-26a3-4889-b047-79d87439d53b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::div[7]</value>
      <webElementGuid>0eaa7d79-4efc-4a27-80cb-1790349fd75c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Mode'])[1]/following::div[21]</value>
      <webElementGuid>0f599e0e-6003-4c83-a185-720ce54d21b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in with email'])[1]/preceding::div[3]</value>
      <webElementGuid>3480f026-6193-4179-b0f6-778ccb1faede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign in with Google']/parent::*</value>
      <webElementGuid>faf262bf-4140-43f3-89bb-67c22f129517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div[2]</value>
      <webElementGuid>b5027524-252a-4f0d-99e7-dcfd215fc7a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sign in with Google' or . = 'Sign in with Google')]</value>
      <webElementGuid>15cd3900-c015-428a-b220-c278ba2a7dc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
