<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_OR_style-prefix-ue3i0g</name>
   <tag></tag>
   <elementGuidId>0e1ed5c8-08a1-45b3-9616-9f1e96ac931d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='phoneloginModal']/div[3]/div/div/div[2]/div/div[2]/div[3]/button/div/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.style-prefix-ue3i0g</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>607c2002-1059-4b63-ae8b-47e853a0c1ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn-images.cure.fit/www-curefit-com/image/upload/c_fill,w_24,ar_1,q_auto:eco,dpr_2,f_auto,fl_progressive//image/cultsport/assets/google-logo.png</value>
      <webElementGuid>47e658ca-6c51-4b22-a4d9-de34d5c993c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-prefix-ue3i0g</value>
      <webElementGuid>dbb2f279-aa69-43da-bf9e-0b9fd0c28d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phoneloginModal&quot;)/div[@class=&quot;style-prefix-pbmsma&quot;]/div[@class=&quot;style-prefix-17k3sa9&quot;]/div[@class=&quot;style-prefix-lv607q&quot;]/div[@class=&quot;style-prefix-mfhl81&quot;]/div[@class=&quot;style-prefix-1j61q1z&quot;]/div[@class=&quot;style-prefix-1nr9jr0&quot;]/div[@class=&quot;style-prefix-qtcbab&quot;]/button[@class=&quot;style-prefix-ozt8il&quot;]/div[@class=&quot;button_text style-prefix-zmnbeb&quot;]/div[@class=&quot;style-prefix-x4dmss&quot;]/div[@class=&quot;style-prefix-7kp13n&quot;]/img[@class=&quot;style-prefix-ue3i0g&quot;]</value>
      <webElementGuid>6ae38339-d27f-4caa-be31-88362a3d8430</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='phoneloginModal']/div[3]/div/div/div[2]/div/div[2]/div[3]/button/div/div/div[2]/img</value>
      <webElementGuid>4c97c844-f65d-4089-976a-b19b6025c3f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://cdn-images.cure.fit/www-curefit-com/image/upload/c_fill,w_24,ar_1,q_auto:eco,dpr_2,f_auto,fl_progressive//image/cultsport/assets/google-logo.png')]</value>
      <webElementGuid>cf70d9c3-8070-4167-bf6c-f8f3cdf545ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div/div[2]/img</value>
      <webElementGuid>8fcd0bed-d5d6-4f7e-8bad-a516823e355b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn-images.cure.fit/www-curefit-com/image/upload/c_fill,w_24,ar_1,q_auto:eco,dpr_2,f_auto,fl_progressive//image/cultsport/assets/google-logo.png']</value>
      <webElementGuid>f17fbcc2-6de3-46fa-8d99-3379d0fae281</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
