<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sports Shoes_style-prefix-1iji7yj</name>
   <tag></tag>
   <elementGuidId>e5f44425-62fe-480c-b947-0128778e6192</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='plp-container']/div[2]/div/div/a/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>51efa4b7-c9d2-403d-b832-05c5ad6100d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn-images.cure.fit/www-curefit-com/image/upload/fl_progressive,f_auto,q_auto:eco,w_300,h_400,ar_0.75,c_fill/dpr_2/cultgear-content/ifxQqSatbw9anqJsmG1eo1SA</value>
      <webElementGuid>c2f2da81-0de4-4e59-ba33-bb1f09e1d9f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Flomo Women Running Shoe</value>
      <webElementGuid>a6632461-06dc-4151-8db7-e572ca6d110e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> style-prefix-1iji7yj</value>
      <webElementGuid>c6ae5095-4798-47a7-bd28-997cbdaae4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>cefb61df-0e7d-4985-a640-3d2945958f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>72b1e84f-8692-4a32-882a-9bae859d6277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>aea4b75c-9187-4440-990d-e3059195baeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;plp-container&quot;)/div[@class=&quot;animate-tb&quot;]/div[@class=&quot;style-prefix-ikbfam&quot;]/div[@class=&quot;col-xs-6 col-lg-3 col-md-3 col-sm-6 animate-tb noPadding style-prefix-prstg&quot;]/a[@class=&quot;style-prefix-0&quot;]/div[@class=&quot;style-prefix-12pfcno&quot;]/div[@class=&quot;style-prefix-xcvqlr&quot;]/img[@class=&quot;style-prefix-1iji7yj&quot;]</value>
      <webElementGuid>a856598b-7d96-46a0-b528-3dd90397820c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='plp-container']/div[2]/div/div/a/div/div/img</value>
      <webElementGuid>1e490ff4-7d26-4590-99dd-bbd77b68fd34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Flomo Women Running Shoe']</value>
      <webElementGuid>1bc9336b-8432-44f7-bad8-9f92ea440c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div/img</value>
      <webElementGuid>5ea13ee4-792e-4af6-afe9-9ee0993d40df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn-images.cure.fit/www-curefit-com/image/upload/fl_progressive,f_auto,q_auto:eco,w_300,h_400,ar_0.75,c_fill/dpr_2/cultgear-content/ifxQqSatbw9anqJsmG1eo1SA' and @alt = 'Flomo Women Running Shoe']</value>
      <webElementGuid>7977f96d-93bb-4b9a-bdc9-15fe8b9e16c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
