<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Or connect with_style-prefix-ue3i0g</name>
   <tag></tag>
   <elementGuidId>3b87cebd-d9b0-45c6-b4c1-fdf6ffce4ec7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='phoneloginModal']/div[3]/div/div/div[2]/div/div[2]/div[3]/button/div/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.style-prefix-ue3i0g</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c7c84a0a-9ac5-4e24-9f8c-1c9b7653f9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn-images.cure.fit/www-curefit-com/image/upload/c_fill,w_24,ar_1,q_auto:eco,dpr_2,f_auto,fl_progressive//image/login/google-login-white.svg</value>
      <webElementGuid>cda42ae4-d5d8-44cc-bcc9-fef42280e654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-prefix-ue3i0g</value>
      <webElementGuid>d407c013-e6f7-43b7-b1da-b252d06c67fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phoneloginModal&quot;)/div[@class=&quot;style-prefix-pbmsma&quot;]/div[@class=&quot;style-prefix-17k3sa9&quot;]/div[@class=&quot;style-prefix-4f0zv4&quot;]/div[@class=&quot;style-prefix-mfhl81&quot;]/div[@class=&quot;style-prefix-a9b9gc&quot;]/div[@class=&quot;style-prefix-3r6lhh&quot;]/div[@class=&quot;style-prefix-qtcbab&quot;]/button[@class=&quot;style-prefix-ozt8il&quot;]/div[@class=&quot;button_text style-prefix-14wm3zd&quot;]/div[@class=&quot;style-prefix-gg4vpm&quot;]/div[@class=&quot;style-prefix-7kp13n&quot;]/img[@class=&quot;style-prefix-ue3i0g&quot;]</value>
      <webElementGuid>bb2d48ed-d8c4-4213-aa9d-5c8f47fea769</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='phoneloginModal']/div[3]/div/div/div[2]/div/div[2]/div[3]/button/div/div/div[2]/img</value>
      <webElementGuid>40249cb2-d575-4dc7-af41-713be7f9b4f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://cdn-images.cure.fit/www-curefit-com/image/upload/c_fill,w_24,ar_1,q_auto:eco,dpr_2,f_auto,fl_progressive//image/login/google-login-white.svg')]</value>
      <webElementGuid>0cd2bf0c-91c9-44b3-99d4-956eeab5bbdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div/div[2]/img</value>
      <webElementGuid>2185bc4c-4ff8-4484-9f19-47ae7244bd5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn-images.cure.fit/www-curefit-com/image/upload/c_fill,w_24,ar_1,q_auto:eco,dpr_2,f_auto,fl_progressive//image/login/google-login-white.svg']</value>
      <webElementGuid>b0c09956-3ee3-4bbb-9420-47d1262e5e30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
