<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Cultsport Elite 100 Whey Protein, 1 Kg__b60bcd</name>
   <tag></tag>
   <elementGuidId>4e9d0682-c9bc-4a5b-b75e-c59f26d2f844</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='plp-container']/div[2]/div/div[3]/a/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>94c1a31b-b151-4c4d-9452-49676950bdb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn-images.cure.fit/www-curefit-com/image/upload/fl_progressive,f_auto,q_auto:eco,w_300,h_400,ar_0.75,c_fill/dpr_2/cultgear-content/VDxmyWjWBtLAsoecqfLURGkg</value>
      <webElementGuid>d8ef0d8f-a5c7-438c-a9b6-43b2507f3611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Cultsport Elite Whey Isolate Protein, 908g</value>
      <webElementGuid>546702a2-64e8-4dc0-ad1f-8af318e5c919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> style-prefix-1iji7yj</value>
      <webElementGuid>0927cc74-d854-4918-b4c3-5c89c773a6ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>dd0225d8-7b64-4b28-b18f-8f2141f6dfaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>a4d3e4bd-716d-4b51-8c78-5a35b0ff6811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>4d5f44da-4da1-4951-b25f-893f08c6bf45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;plp-container&quot;)/div[@class=&quot;animate-tb&quot;]/div[@class=&quot;style-prefix-ikbfam&quot;]/div[@class=&quot;col-xs-6 col-lg-3 col-md-3 col-sm-6 animate-tb noPadding style-prefix-prstg&quot;]/a[@class=&quot;style-prefix-0&quot;]/div[@class=&quot;style-prefix-12pfcno&quot;]/div[@class=&quot;style-prefix-xcvqlr&quot;]/img[@class=&quot;style-prefix-1iji7yj&quot;]</value>
      <webElementGuid>9084ba89-49b7-4ccf-8b93-8882fb82bb28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='plp-container']/div[2]/div/div[3]/a/div/div/img</value>
      <webElementGuid>d047139a-b5b4-49f0-a544-dc653810ccc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Cultsport Elite Whey Isolate Protein, 908g']</value>
      <webElementGuid>e357c3f4-3c22-4ad1-9a4a-d2698ef83180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/div/div/img</value>
      <webElementGuid>db38a08d-3ca2-48ed-be8b-76d4d543f670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn-images.cure.fit/www-curefit-com/image/upload/fl_progressive,f_auto,q_auto:eco,w_300,h_400,ar_0.75,c_fill/dpr_2/cultgear-content/VDxmyWjWBtLAsoecqfLURGkg' and @alt = 'Cultsport Elite Whey Isolate Protein, 908g']</value>
      <webElementGuid>edf8b64a-7a90-4c25-8c81-dcb93ef92869</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
